# Minecraft Bedrock Home Control – Proxmox Konfiguration
# -------------------------------------------------------
[config]
PROXMOX_HOST    = https://localhost:8006
PROXMOX_NODE    = pve
API_TOKEN_ID    = autostopper@pve!mc-stop
API_TOKEN_SEC   = DEIN-TOKEN-SECRET-HIER

MC_PORT         = 19132
IDLE_TIMEOUT    = 300
CHECK_INTERVAL  = 15
MC_BEDROCK_TAG  = mc-bedrock
MC_AUTOSTOP_TAG = mc-autostop

WEB_ENABLED     = true
WEB_HOST        = 0.0.0.0
WEB_PORT        = 8123
